name: Manual trigger!
on:
  workflow_call:

jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Run unit tests
        run: pnpm run test

      - name: Greeting
        run: echo "Good work Automatic Job are finished" >> $GITHUB_STEP_SUMMARY